### PR TITLE
changes the kinesis version to 1.6.1

### LINKED ISSUE #1: no such file to load -- logstash-input-kinesis_jars
tried using this gem but getting `no such file to load -- logstash-input-kinesis_jars` . 

 `logstash-input-kinesis_jars` is added to https://github.com/codekitchen/logstash-input-kinesis/blob/master/.gitignore and hence it is not working

### LINKED ISSUE #2: Error processing record.getData: java.nio.HeapByteBuffer[pos=0 lim=611 cap=611]
Any idea why we get this error when trying to use the plugin?

:message=>"Error processing record.getData: java.nio.HeapByteBuffer[pos=0 lim=611 cap=611]", :level=>:error, :file=>"logstash/inputs/kinesis/worker.rb", :line=>"68", :method=>"process_record"

Thanks

### PR DESCRIPTION
**Pull request by samuelgmartinez**
This version change allows the consumer to [deaggregate](http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-kpl-consumer-deaggregation.html) the messages sent by the [KPL](https://github.com/awslabs/amazon-kinesis-producer/blob/master/aggregation-format.md) (available since 1.4.0 if I recall correctly).

This also lowers the number of library dependencies, since the current versions of Kinesis client doesn't depends on the full aws-sdk anymore.

This fixes #2  probably related to the de/aggregation feature.

### CODE REVIEW

**Comment by samuelgmartinez** [comment]
I'm trying to fix the tests right now. 

I'll update the branch when its all fixed.

**Comment by samuelgmartinez** [comment]
Due to the changes made on the API and the new interfaces some asserts are no longer possible, so I have to rewrite the worker to use the new interface (.v2 package).

I will get in to it tomorrow morning (CEST)

**Comment by codekitchen** [comment]
Ah we don't use the KPL anywhere yet, so I wasn't even aware of the newer aggregation functionality. Thanks for sorting that out.

Looking at http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-record-processor-implementation-app-java.html#kcl-java-v2-migration it doesn't look like migrating to the v2 record processor interface involves too much work, but let me know if you run into anything I can help with.

**Comment by samuelgmartinez** [comment]
Thanks for offering you help. I don't have a clue about Ruby programming but I'm trying my best.

when I upload the changes, please, let me know all the errors I made to fix them :D

**Comment by samuelgmartinez** [comment]
Fixed! I'm sure this is not the best way to do it, so feel free to change or tell me what I should change to get this PR merged :)

Thanks for your help!

File: lib/logstash/inputs/kinesis/worker.rb [hunk 1]
```diff
@@ -16,22 +16,22 @@ def initialize(*args)
...
+      checkpoint(records_input.checkpointer)
       @next_checkpoint = Time.now + @checkpoint_interval
     end
   end
 
-  def shutdown(checkpointer, reason)
-    if reason == com.amazonaws.services.kinesis.clientlibrary.types::ShutdownReason::TERMINATE
+  def shutdown(shutdown_input)
+    if shutdown_input.reason == com.amazonaws.services.kinesis.clientlibrary.types::ShutdownReason::TERMINATE
       checkpoint(checkpointer)
```
Comment (codekitchen) [inline lib/logstash/inputs/kinesis/worker.rb]: i think this needs to change to `shutdown_input.checkpointer` right?

Comment (samuelgmartinez) [inline lib/logstash/inputs/kinesis/worker.rb]: yes! You are right. I've already pushed that fix.

I think this method should be tested somehow.

File: lib/logstash/inputs/kinesis.rb [hunk 2]
```diff
@@ -49,8 +51,15 @@ class LogStash::Inputs::Kinesis < LogStash::Inputs::Base
   # to enable the cloudwatch integration in the Kinesis Client Library.
   config :metrics, :validate => [nil, "cloudwatch"], :default => nil
 
-  def initialize(params = {}, kcl_class = KCL::Worker)
-    @kcl_class = kcl_class
+  #what a nasty hack to use the overloaded method :_(
+  java_import KCL::Worker::Builder
+  class Builder
+    #I don't know how to make it work using the class directly
+    java_alias :v2RecordProcessorFactory, :recordProcessorFactory, [Java::JavaClass.for_name(KCL_PROCESSOR_FACTORY_CLASS)]
```
Comment (codekitchen) [inline lib/logstash/inputs/kinesis.rb:58]: can you explain this? i'm reading it as you are modifying the `KCL::Worker::Builder` class to alias `recordProcessorFactory` -> to `v2RecordProcessorFactory`, but i'm not clear on why

Comment (samuelgmartinez) [inline lib/logstash/inputs/kinesis.rb:58]: no idea

Jokes aside, I've used the `java_alias` because, as I learned yesterday you can't overload a method in Ruby (using the same method name with diferent signature), and the KCL Builder now exposes two methods with the name `recordProcessorFactory`: [one](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L687) with the v1 recordProcessorFactory interface (wrapping it with an v1-to-v2 adaptor) and the [good one](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L701) which uses the v2 recordProcessorFactory.

So, in order to preserve the ability to test the worker and to use the v2 API I had to use a java_alias, to map the v2 API method to a new name.

I have to add one note regarding the `JavaClass.for_name`. I didn't find a way to use java classes directly, all I've got were "can not cast RubyModule to a java.lang.Class" errors every time. The line was something like: 

```
java_alias :v2RecordProcessorFactory, :recordProcessorFactory, [com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker::Builder]
```

Maybe adding the `.java_class` method would work:

```
java_alias :v2RecordProcessorFactory, :recordProcessorFactory, [com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker::Builder.java_class]
```

As a disclaimer I have to say that I don't know if this is the way to do this, but I didn't find any other way to hack it.

Comment (codekitchen) [inline lib/logstash/inputs/kinesis.rb:58]: Haha, I know the feeling. JRuby isn't my forte either. I think I see what you are saying now, though it seems like if we updated some of the tests, this could be avoided... I'll take a stab at that later.

Comment (samuelgmartinez) [inline lib/logstash/inputs/kinesis.rb:58]: Ok! Thanks for your help!

I think even changing the tests, you will need to do the alias thing
because the builder needs that you set the processor factory.

Without the alias, in my machine the jvm warned me about the ambiguous
method and picked the v2 implementation. In the container I used for
testing the jvm warned the same message but picked the v1 method. Even
using the same ruby version (2.2.1).

Let me know if you need that I change anything.

Thank you! 😊

Comment (codekitchen) [inline lib/logstash/inputs/kinesis.rb:58]: yep, just discovered that myself :) I'll read up a bit on what can be done.

I'm going to merge this, but I want to test it a bit more before releasing a new gem. Thanks for the help!

**Comment by codekitchen** [comment]
ok this has been released as gem version 1.4.0, thanks again

**Comment by dsolsona** [comment]
Thanks!
